"""Add user_id to Review model

Revision ID: 66801c1500b6
Revises: 821a7815560d
Create Date: 2024-01-25 20:39:47.384398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66801c1500b6'
down_revision = '821a7815560d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
