"""user review relationship

Revision ID: 821a7815560d
Revises: db157f290e06
Create Date: 2024-01-25 20:14:23.409390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821a7815560d'
down_revision = 'db157f290e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_review_house_id', 'house', ['house_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_house_id', type_='foreignkey')
        batch_op.drop_column('house_id')

    # ### end Alembic commands ###
