"""adding url

Revision ID: db157f290e06
Revises: 
Create Date: 2024-01-23 16:28:06.291248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db157f290e06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
